name: Test

run-name: Ensure Test passes on the ${{ github.ref_name }} branch.  ${{ github.event.head_commit.message }}

on: [push]

jobs:
  linux-test:
    name: Run Tests for Linux
    runs-on: linux-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Test
        run: cargo test --features test_helpers,simple,tokio
  macos-test:
    name: Run Tests for macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Test
        run: cargo test --features test_helpers,simple,tokio
  windows-test:
    name: Run Tests for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Test
        run: cargo test --features test_helpers,simple,tokio
